package None;

import java.util.List;
import lombok.*;






/**
  A DataAnalysis which assigns a chemical structure to the peaks of a NMRSpectrum generated by a NMRSpectroscopy
**/
@Data
@EqualsAndHashCode(callSuper=false)
public class NMRSpectralAnalysis extends DataAnalysis {


}