---
name: Publish Python Package

# Publishes with trusted publishing to
# - PyPI on releases created in GitHub UI if status is published.
#   For draft status, nothing happens.
# - TestPyPI on new tags "v1.2.3" or "v1.2.3.something" on main branch
#
# More on trusted publishing: https://docs.pypi.org/trusted-publishers/

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      # GitHub glob matching is limited [1]. So we can't define a pattern matching
      # pep 440 version definition [N!]N(.N)*[{a|b|rc}N][.postN][.devN]
      - 'v[0-9]+.[0-9]+.[0-9]+.?*'
  release:
    types: [published]

permissions: {}

jobs:
  build:
    name: Build Python 🐍 distributions 📦 for publishing
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
        with:
          python-version: 3.9

      - name: Install just & poetry incl. plugins
        # We install poetry-dynamic-versioning into pipx because the automatic
        # install by poetry 2.x triggers a Windows issue
        # https://github.com/pypa/installer/issues/260
        # and also does not work on Ubuntu in gh-actions.
        run: |
          pipx install rust-just
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Build source and wheel archives
        run: poetry build

      - name: Store built distribution
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: distribution-files
          path: dist/

  pypi-publish:
    name: Build and publish Python 🐍 package 📦 to PyPI and TestPyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
      url: https://pypi.org/p/dcat_4c_ap
    permissions:
      id-token: write  # this permission is mandatory for trusted publishing
    steps:
      - name: Download built distribution
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
        with:
          name: distribution-files
          path: dist

      - name: Publish package 📦 to Test PyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Publish package 📦 to PyPI
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          verbose: true

# [1] https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
# Used actions: (updates managed by dependabot)
# - https://github.com/actions/checkout
# - https://github.com/actions/setup-python
# - https://github.com/actions/upload-artifact
# - https://github.com/actions/download-artifact
# - https://github.com/pypa/gh-action-pypi-publish/
